### ISSUE TITLE
Update `record-studio`

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript/registry#59]
```json
{
  "name": "record-studio",
  "ref": "v1.0.1",
  "compiler": "0.15.4"
}
```

**Comment by i-am-the-slime** [comment]
Did I do this wrong?

**Comment by thomashoneyman** [comment]
Sorry, we made a change to the codebase that messed up a path. It’s fixed now and I’ll restart this.

**Comment by i-am-the-slime** [comment]
Faster than the police allows!

**Comment by MonoidMusician** [comment]
Huh, that didn't fix it. Is there a location I missed? What's happening is that it is interpreting `v1/Manifest` as a variable since it doesn't have any `./` or `../` at the beginning....

**Comment by MonoidMusician** [comment]
Ohhh wait, `Path.concat` or something in there probably normalizes the path, no?

**Comment by thomashoneyman** [comment]
This is alpha software, people!

**Comment by i-am-the-slime** [comment]
@thomashoneyman 
> This is alpha software, people!

It's still really cool 😎
